{% set name = "validobj" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f60847194cfaf9eed6d1870e6e166716675907741b765731bf7d2e3e2c34b27

build:
  noarch: python
  number: 0
  script: flit install

requirements:
  host:
    - python >=3.7
    - flit
  run:
    - python >=3.7

test:
  imports:
    - validobj

about:
  home: https://github.com/Zaharid/validobj
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Validobj gives you valid objects

  description: |
    Validobj is library that takes semistructured data (for example JSON and YAML
    configuration files) and converts it to more structured Python objects. It
    places the emphasis on:

      - [Good error messages](https://validobj.readthedocs.io/en/latest/errors.html)
        (rather than avoiding extra work in the error handling
        code).
      - Schema defined in terms of
        [dataclasses](https://docs.python.org/3/library/dataclasses.html) and other
        high level objects such as
        [enums](https://docs.python.org/3/library/enum.html), as well as a subset of
        the [typing](https://docs.python.org/3/library/typing.html) module.
      - Simplicity of implementation (rather than full generality).

    Validobj requires Python 3.7 and has no other dependencies.
  doc_url: https://validobj.readthedocs.io/
  dev_url: https://github.com/Zaharid/validobj

extra:
  recipe-maintainers:
    - Zaharid
